"""init

Revision ID: 32244c477f92
Revises: 17a80f9aa91c
Create Date: 2026-02-03 23:01:22.912392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32244c477f92'
down_revision: Union[str, Sequence[str], None] = '17a80f9aa91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ten_k_filings',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(), nullable=False),
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('10KFilings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('10KFilings',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('10KFilings_pkey'))
    )
    op.drop_table('ten_k_filings')
    # ### end Alembic commands ###
